# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: weather.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='weather.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\rweather.proto\"\x14\n\x04\x43ity\x12\x0c\n\x04name\x18\x01 \x01(\t\"O\n\x07Weather\x12\x12\n\nconditions\x18\x01 \x01(\t\x12\x0c\n\x04temp\x18\x02 \x01(\x02\x12\x10\n\x08humidity\x18\x03 \x01(\x02\x12\x10\n\x08pressure\x18\x04 \x01(\x02\"=\n\x0b\x43ityWeather\x12\x13\n\x04\x63ity\x18\x01 \x01(\x0b\x32\x05.City\x12\x19\n\x07weather\x18\x02 \x03(\x0b\x32\x08.Weather21\n\nWeatherApp\x12#\n\nGetWeather\x12\x05.City\x1a\x0c.CityWeather\"\x00\x62\x06proto3'
)




_CITY = _descriptor.Descriptor(
  name='City',
  full_name='City',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='City.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=17,
  serialized_end=37,
)


_WEATHER = _descriptor.Descriptor(
  name='Weather',
  full_name='Weather',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='conditions', full_name='Weather.conditions', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temp', full_name='Weather.temp', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='humidity', full_name='Weather.humidity', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pressure', full_name='Weather.pressure', index=3,
      number=4, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=39,
  serialized_end=118,
)


_CITYWEATHER = _descriptor.Descriptor(
  name='CityWeather',
  full_name='CityWeather',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='city', full_name='CityWeather.city', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='weather', full_name='CityWeather.weather', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=181,
)

_CITYWEATHER.fields_by_name['city'].message_type = _CITY
_CITYWEATHER.fields_by_name['weather'].message_type = _WEATHER
DESCRIPTOR.message_types_by_name['City'] = _CITY
DESCRIPTOR.message_types_by_name['Weather'] = _WEATHER
DESCRIPTOR.message_types_by_name['CityWeather'] = _CITYWEATHER
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

City = _reflection.GeneratedProtocolMessageType('City', (_message.Message,), {
  'DESCRIPTOR' : _CITY,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:City)
  })
_sym_db.RegisterMessage(City)

Weather = _reflection.GeneratedProtocolMessageType('Weather', (_message.Message,), {
  'DESCRIPTOR' : _WEATHER,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:Weather)
  })
_sym_db.RegisterMessage(Weather)

CityWeather = _reflection.GeneratedProtocolMessageType('CityWeather', (_message.Message,), {
  'DESCRIPTOR' : _CITYWEATHER,
  '__module__' : 'weather_pb2'
  # @@protoc_insertion_point(class_scope:CityWeather)
  })
_sym_db.RegisterMessage(CityWeather)



_WEATHERAPP = _descriptor.ServiceDescriptor(
  name='WeatherApp',
  full_name='WeatherApp',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=183,
  serialized_end=232,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetWeather',
    full_name='WeatherApp.GetWeather',
    index=0,
    containing_service=None,
    input_type=_CITY,
    output_type=_CITYWEATHER,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_WEATHERAPP)

DESCRIPTOR.services_by_name['WeatherApp'] = _WEATHERAPP

# @@protoc_insertion_point(module_scope)
