# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import weather_pb2 as weather__pb2


class WeatherAppStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWeather = channel.unary_unary(
                '/WeatherApp/GetWeather',
                request_serializer=weather__pb2.City.SerializeToString,
                response_deserializer=weather__pb2.CityWeather.FromString,
                )


class WeatherAppServicer(object):
    """Missing associated documentation comment in .proto file"""

    def GetWeather(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeatherAppServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWeather': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeather,
                    request_deserializer=weather__pb2.City.FromString,
                    response_serializer=weather__pb2.CityWeather.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WeatherApp', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WeatherApp(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def GetWeather(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/WeatherApp/GetWeather',
            weather__pb2.City.SerializeToString,
            weather__pb2.CityWeather.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
